import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const poppins = Poppins({ subsets: ["latin"], weight: ['400','500','700','900'] });

export const metadata: Metadata = {
  title: "Hotel Management",
  description: "Generated by create next app", 
  style: ['italic','normal'],
  varaible: '--font-poppins',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="font-normal">
          <Header />
          {children}
          {/* ?Footer */}
        </main>
      </body>
    </html>
  );
}
